### ISSUE TITLE
Including state dependent actions in model

### ISSUE THREAD

**Issue by bpleao** [JuliaPOMDP/quickpomdps#10]
@zsunberg I've been using quickpomdps successfully with a fixed set of actions. Now I need to use state dependent actions as described in [documentation](https://juliapomdp.github.io/QuickPOMDPs.jl/stable/quick/#Keyword-arguments-may-be-functions-or-objects-1) but I get errors when I try to do so. I've tested it by modifying the Light-Dark problem as below:
``` python
def actions(s):
    if s > 0:
        return [-12, -2, 0, 1, 10] 
    else:
        return [-10, -1, 0, 2, 12] 

m = QuickPOMDP(
    states = range(-r, r+2),
    actions = actions,
    discount = 0.95,
    isterminal = lambda s: s < -r or s > r,
    obstype = Float64,
    transition = transition,
    observation = observation,
    reward = reward,
    initialstate = Uniform(range(-r//2, r//2+1))
)
```
and I get the following error when running QuickPOMDP:
```
TypeError: actions() missing 1 required positional argument: 's'
```

**Comment by zsunberg** [comment]
Unfortunately some solvers may not support state dependent actions and sometimes even solvers that do support state-dependent actions need a list of all the actions. Therefore the best practice is to provide an actions function with an *optional* state argument

**Comment by zsunberg** [comment]
I.e. something like

```
def actions(s=None):
    if s===None:
        return [-12,-10,-2,-1,0,1,2,10,12]
    elif s > 0:
        return [-12, -2, 0, 1, 10] 
    else:
        return [-10, -1, 0, 2, 12] 
```
