### ISSUE TITLE
Unable to install quickpomdps with pip

### ISSUE THREAD

**Issue by alphonsusadubredu** [JuliaPOMDP/quickpomdps#2]
I'm unable to install the quickpomdps package with `pip install quickpomdps`.
I'm using Python3.6. 

Thank you.

**Comment by zsunberg** [comment]
I unfortunately don't have time to fix this at the moment - hopefully in the near future I will have the resources and/or someone else will be able to step in and help.

**Comment by zsunberg** [comment]
It should be possible to get most of the functionality through pycall, e.g. https://github.com/JuliaPOMDP/QuickPOMDPs.jl/blob/master/examples/tiger.py

**Comment by alphonsusadubredu** [comment]
That worked. Thanks!

**Comment by rejuvyesh** [comment]
@alphonsusadubredu could you share the error you got?
